"""Build data/page-map.json from guideline_catalogue.json.

The catalogue lists, for every topic, the printed page ("chapter.page") and the PDF page of the book it came from.
One numeric offset per book cannot resolve STG cites (the hospital STG is split over four PDFs and every chapter starts
at a different PDF page), but inside one chapter the offset is constant. So the app only needs, per book and chapter:
which catalogue document holds it, and that chapter's offset.  PDF page = printed page + offset.

Usage:  python tools/build_page_map.py [path/to/guideline_catalogue.json]
        (default: PocketDoc/Guidelines/guideline_catalogue.json next to the repo's Documents folder)
It refuses to write if any chapter shows drift or spans more than one document.
"""
import collections, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__))
DEFAULT = r"C:\Users\jharm\OneDrive\Documents\PocketDoc\Guidelines\guideline_catalogue.json"
src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT
out = os.path.join(HERE, "..", "data", "page-map.json")

# catalogue document -> app source id (sources.json). HOSP1-4 are the four PDFs of the adult hospital STG.
BOOK = {"HOSP1": "stg-adult", "HOSP2": "stg-adult", "HOSP3": "stg-adult", "HOSP4": "stg-adult", "PAED": "stg-paed", "PHC": "PHC"}

cat = json.load(open(src, encoding="utf-8"))
docs = {d["id"]: d for d in cat["documents"]}
seen = collections.defaultdict(set)  # (book, chapter) -> {(doc, offset)}
for t in cat["topics"]:
    if t["doc"] not in BOOK:
        continue
    m = re.match(r"^(\d+)\.(\d+)$", str(t["page"]))
    if m:
        seen[(BOOK[t["doc"]], m.group(1))].add((t["doc"], t["pdf_page"] - int(m.group(2))))

books, used = collections.defaultdict(dict), collections.defaultdict(list)
for (book, ch), v in sorted(seen.items(), key=lambda kv: (kv[0][0], int(kv[0][1]))):
    if len(v) != 1:
        sys.exit("chapter %s of %s is not a single (document, offset): %s" % (ch, book, sorted(v)))
    doc, off = next(iter(v))
    books[book][ch] = [doc, off]
    used[doc].append(int(ch))

def span(c):
    c = sorted(c)
    return "%d" % c[0] if len(c) == 1 else "%d–%d" % (c[0], c[-1])

doc_out = {}
for doc, chs in used.items():
    d = docs[doc]
    doc_out[doc] = {"file": os.path.basename(d["file"]), "pages": d["pdf_pages"], "chapters": span(chs), "title": re.sub(r"[^\x20-\x7e]+", "-", d["title"]).strip()}

result = {"built": cat["meta"]["built"], "note": "PDF page = printed page + offset. books[source id][chapter] = [catalogue document, offset]. Generated by tools/build_page_map.py - do not edit by hand.",
          "docs": doc_out, "books": books}
with open(out, "w", encoding="utf-8", newline="\n") as f:
    json.dump(result, f, ensure_ascii=False, separators=(",", ":"))
    f.write("\n")
print("wrote", os.path.normpath(out), os.path.getsize(out), "bytes;", sum(len(b) for b in books.values()), "chapters;", len(doc_out), "documents")
